# This file was generated by SQLVault ##########################################

library(divDB)

# Extract ----------------------------------------------------------------------

query <- read_sql("create-iris-db.sql")

# Transform --------------------------------------------------------------------

# Load -------------------------------------------------------------------------

conn <- connect_db(dbname = "iris-db", user = "miguel")
dbSendQuery(conn, query)
disconnect_db(conn)

# Test -------------------------------------------------------------------------
