# This file was generated by SQLVault ##########################################

library(DBI)
library(divDB)

# Extract ----------------------------------------------------------------------

full_names <- data.frame(species = c("setosa", "versicolor", "virginica"),
                         name = c(
                           "Iris setosa",
                           "Iris versicolor",
                           "Iris virginica"
                         ),
                         author = c(
                           "Pall. ex Link",
                           "L.",
                           "L."
                         ))

# Transform --------------------------------------------------------------------

conn <- connect_db(dbname = "iris-db", user = "miguel")

ref_table <- dbGetQuery(conn, "select * from data_frames.iris")
#full_names <- merge(ref_table, full_names)

# Load -------------------------------------------------------------------------

query <- add_columns(conn, df = data.frame(
    name = c("name", "author"),
    type = c("text", "text"),
    comment = c("Scientific name.", "Author of scientific name.")),
  name = c("data_frames", "iris"),
  eval = TRUE)

query <- c(query, update_rows(conn, y = full_names, key = "species",
            name = c("data_frames", "iris"), eval = TRUE))

query <- as(query, "sql")
query

# Restore and write query
do_restore(dbname = "iris-db", user = "miguel", filepath = "../iris-backups")
write_sql(query, file = "update-iris-db.sql")

# Test -------------------------------------------------------------------------



