#' @name build_db
#'
#' @title Restore a Database from a released backup
#'
#' @description
#' Releases are a collection of backups generated by [release_project()].
#' After displaying them with [backups_info()], you may desire to restore a
#' determined version of the database.
#'
#' @param dbname A character value with the name of the database where to
#'     restore. Note that this database should be created in advance, otherwise
#'     you will retrieve an error message.
#' @param user A character value with the name of the user.
#' @param backup_path A character value with the path to the folder containing
#'     backups.
#' @param release An integer value indicating the sort order according to
#'     [backups_info()]. The keywords "first" and "last" are also accepted.
#'     The default value is "last".
#' @param ... Further arguments passed to [divDB::do_restore()].
#'
#' @export
build_db <- function(dbname, user, backup_path, release = "last", ...) {
  db_info <- backups_info(backup_path = backup_path)
  if (release == "last") {
    release <- db_info$sort[nrow(db_info)]
  } else if (release == "first") {
    release <- db_info$sort[1]
  }
  # Eventually build more checks
  # Restore the database
  divDB::do_restore(
    dbname = dbname, user = user,
    backup = file.path(backup_path, db_info$backup[release]), ...
  )
}
